<?php if (LOGGEDIN) { ?>
					<div id="user_nav" class="btn-group pull-right">
						<?php echo HTML::link('<i class="icon-user"></i> '.l('usercp'), '/usercp', array('class' => 'btn')); ?>
<?php if ($current_user->group->is_admin) { ?>
						<?php echo HTML::link('<i class="icon-cog"></i> '.l('admincp'), '/admin', array('class' => 'btn')); ?>
<?php } ?>
						<?php echo HTML::link('<i class="icon-off icon-white"></i>', '/logout', array('class' => 'btn btn-inverse')); ?>
					</div>
<?php } else { ?>

<?php if ( ! active_nav('/login')): ?>
					<form action="<?php echo Request::base('login'); ?>" method="post" class="navbar-form form-inline pull-right">
						<?php echo Form::text('username', array('placeholder' => l('username'), 'class' => 'input-medium')); ?>
						<?php echo Form::password('password', array('placeholder' => l('password'), 'class' => 'input-medium')); ?>
						<div class="btn-group">
							<?php echo Form::submit(l('login'), 'login', array('class' => 'btn')); ?>
							<?php echo HTML::link(l('register'), '/register', array('class' => 'btn btn-inverse')); ?>
						</div>
					</form>
<?php endif ?>
<?php } ?>