<!DOCTYPE html>
<html>
	<head>
		<?php echo View::render('layouts/_head'); ?>
		<?php FishHook::run('template:layouts/default/head'); ?>
	</head>
	<body>
		<header id="header" class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
<?php echo (isset($project))
	? View::render('layouts/_project_switcher')
	: HTML::link(settings('title'), null, array('class' => 'brand')); ?>

					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>

<?php echo View::render('layouts/_meta_nav'); ?>

					<nav id="nav" class="nav-collapse collapse">
						<ul id="main_nav" class="nav">
<?php if (isset($project)) { ?>
							<li<?php echo iif(active_nav('/:slug/timeline'), ' class="active"')?>><?php echo HTML::link(l('timeline'), $project->href("timeline")); ?></li>
							<li<?php echo iif(active_nav('/:slug/(roadmap|milestone)(.*)'), ' class="active"')?>><?php echo HTML::link(l('roadmap'), $project->href("roadmap")); ?></li>
							<li<?php echo iif(active_nav('/:slug/tickets(?:/[0-9]+)?'), ' class="active"')?>><?php echo HTML::link(l('tickets'), $project->href("tickets")); ?></li>
<?php 	if($current_user->permission($project->id, 'create_tickets')) { ?>
							<li<?php echo iif(active_nav('/:slug/tickets/new(.*)'), ' class="active"')?>><?php echo HTML::link(l('new_ticket'), $project->href('tickets/new')); ?></li>
<?php 	} ?>
							<li<?php echo iif(active_nav('/:slug/changelog'), ' class="active"')?>><?php echo HTML::link(l('changelog'), $project->href('changelog')); ?></li>
<?php 	if ($project->enable_wiki) { ?>
							<li<?php echo iif(active_nav('/:slug/wiki(.*)'), ' class="active"')?>><?php echo HTML::link(l('wiki'), $project->href("wiki")); ?></li>
<?php 	} ?>
<?php 	if($current_user->permission($project->id, 'project_settings')) { ?>
							<li<?php echo iif(active_nav('/:slug/settings(.*)'), ' class="active"')?>><?php echo HTML::link(l('settings'), $project->href("settings")); ?></li>
<?php 	} ?>
<?php } ?>
<?php FishHook::run('template:layouts/default/main_nav', array(isset($project) ? $project : false)); ?>
						</ul>
					</nav>

<?php if (isset($project)): ?>
					<form onsubmit="do_search();return false;" id="search" class="navbar-form form-search form-inline">
						<input type="search" name="search" class="search-query input-medium" placeholder="<?php echo l('search'); ?>">
						<input type="hidden" name="project_slug" value="<?php echo $project->slug; ?>" >
					</form>
<?php endif ?>
				</div>
			</div>
		</header>

		<div id="page" class="container">
<?php echo $output; ?>
		</div>

		<footer id="footer" class="container"><?php echo l('copyright', TRAQ_VER, date("Y")); ?></footer>

		<!-- <?php echo round((microtime(true) - START_TIME), 2); ?>s, <?php echo round((memory_get_peak_usage() - START_MEM) / pow(1024, 2), 3); ?>mb -->
	</body>
</html>
