	<h2 id="page_title" class="muted"><?php echo l('usercp'); ?></h2>

<?php echo View::render('usercp/_nav'); ?>

<?php echo show_errors($user->errors); ?>
	<form action="<?php echo Request::requestUri(); ?>" method="post" class="form-horizontal">
		<fieldset id="info">
			<legend><?php echo l('information'); ?></legend>

			<div class="control-group">
				<?php echo Form::label(l('name'), 'name', array('class' => 'control-label')); ?>
				<div class="controls">
					<?php echo Form::text('name', array('value' => $user->name, 'class' => 'input-xlarge')); ?>
				</div>
			</div>
			<div class="control-group">
				<?php echo Form::label(l('email'), 'email', array('class' => 'control-label')); ?>
				<div class="controls">
					<?php echo Form::text('email', array('value' => $user->email, 'class' => 'input-xlarge')); ?>
				</div>
			</div>
			<div class="control-group">
				<?php echo Form::label(l('api_key'), 'api_key', array('class' => 'control-label')); ?>
				<div class="controls controls-row">
				<div class="input-append">
					<?php if ($user->api_key != null) { ?>
						<?php echo Form::text('user_api_key', array('value' => $user->api_key, 'readonly' => true, 'class' => 'input-xlarge')); ?>
					<?php } ?>
					<?php echo HTML::link(l($user->api_key != null ? 'renew' : 'create'), 'usercp/create_api_key', array('class' => 'btn')); ?>
				</div>
				</div>
			</div>
				<?php FishHook::run('template:users/usercp/info'); ?>
		</fieldset>

		<fieldset id="options">
			<legend><?php echo l('options'); ?></legend>
			<div class="control-group">
				<div class="controls">
					<?php echo Form::label(Form::checkbox('watch_created_tickets', 1, array('checked' => $user->option('watch_created_tickets') ? true : false)).' '.l('watch_my_new_tickets'), 'watch_my_new_tickets', array('class' => 'checkbox')); ?>
				</div>
			</div>
			<div class="control-group">
				<?php echo Form::label(l('language'), 'locale', array('class' => 'control-label')); ?>
				<div class="controls">
					<?php echo Form::select('locale', locale_select_options(), array('value' => ($user->locale != '') ? $user->locale : settings('locale'), 'class' => 'input-xlarge')); ?>
				</div>
			</div>
		</fieldset>

		<?php FishHook::run('template:users/usercp'); ?>

		<div class="control-group">
			<div class="controls">
				<?php echo Form::submit(l('save'), 'submit', array('class' => 'btn btn-success')); ?>
			</div>
		</div>
	</form>
