	<h2 id="page_title"><?php echo l('usercp'); ?></h2>

<?php echo View::render('usercp/_nav'); ?>

	<?php echo show_errors($user->errors); ?>
	<form action="<?php echo Request::requestUri(); ?>" method="post" class="form-horizontal">
		<fieldset>
			<legend><?php echo l('password'); ?></legend>

			<div class="control-group">
				<?php echo Form::label(l('old_password'), 'old_password', array('class' => 'control-label')); ?>
				<div class="controls">
					<?php echo Form::password('password', array('class' => 'input-xlarge')); ?>
				</div>
			</div>
			<div class="control-group">
				<?php echo Form::label(l('new_password'), 'new_password', array('class' => 'control-label')); ?>
				<div class="controls">
					<?php echo Form::password('new_password', array('class' => 'input-xlarge')); ?>
				</div>
			</div>
			<div class="control-group">
				<?php echo Form::label(l('confirm_password'), 'confirm_password', array('class' => 'control-label')); ?>
				<div class="controls">
					<?php echo Form::password('confirm_password', array('class' => 'input-xlarge')); ?>
				</div>
			</div>
			<?php FishHook::run('template:users/usercp/password'); ?>
		</fieldset>

		<div class="control-group">
			<div class="controls">
				<?php echo Form::submit(l('save'), 'submit', array('class' => 'btn btn-success')); ?>
			</div>
		</div>
	</form>